export const hexCodes = [
    { colorCode: "#FFFF00", name: "yellow" },
    { colorCode: "#800080", name: "purple" },
    { colorCode: "#FFA500", name: "orange" },
    { colorCode: "#800000", name: "maroon" },
    { colorCode: "#FF00FF", name: "fuschia" },
    { colorCode: "#00FF00", name: "lime" },
    { colorCode: "#00FFFF", name: "aqua" },
    { colorCode: "#008080", name: "teal" },
    { colorCode: "#808000", name: "olive" },
    { colorCode: "#000080", name: "navy" },
    { colorCode: "#FF0000", name: "red" },
    { colorCode: "#008000", name: "green" },
    { colorCode: "#0000FF", name: "blue" },

    { colorCode: "#FFFACD", name: "LemonChiffon" },
    { colorCode: "#FF69B4", name: "HotPink" },
    { colorCode: "#B22222", name: "FireBrick" },
    { colorCode: "#FF7F50", name: "Coral" },
    { colorCode: "#F0F8FF", name: "AliceBlue" },
];
